install.packages("plyr")
install.packages("lubridate")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("dygraphs")
install.packages("xts")
install.packages("ggmap")
install.packages("gridExtra")
install.packages("gtools")
install.packages("rgdal")
install.packages("scales")
install.packages("Cairo")
install.packages("gpclib")
install.packages("maptools")
install.packages("reshape")
install.packages("acs")
install.packages("choroplethrMaps")
install.packages("devtools")

install_github("ropensci/plotly")
install_github("rstudio/leaflet") 
install_github("choroplethr", "trulia")

